"""Updated incorrect model tables

Revision ID: 6dc743ee6e5a
Revises: 
Create Date: 2025-06-26 19:52:36.652402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6dc743ee6e5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.alter_column('addresses', 'longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.add_column('tees', sa.Column('variety', sa.Enum('green', 'green with pergamot', 'rooibos', 'moroccan mint', 'black with forest fruits', 'english breakfast', 'apple'), nullable=True))
    op.alter_column('v_orders_summary', 'latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.alter_column('v_orders_summary', 'longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.drop_column('weird_chocolates', 'temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weird_chocolates', sa.Column('temperature', mysql.ENUM('hot', 'cold'), nullable=False))
    op.alter_column('v_orders_summary', 'longitude',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('v_orders_summary', 'latitude',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.drop_column('tees', 'variety')
    op.alter_column('addresses', 'longitude',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('addresses', 'latitude',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    # ### end Alembic commands ###
