"""Initialise income db migrations

Revision ID: 7a871328ed67
Revises: 
Create Date: 2025-07-01 19:08:20.615955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a871328ed67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v_orders_summary',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_time', sa.Date(), nullable=True),
    sa.Column('tips', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tips_method', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Double(asdecimal=True), nullable=True),
    sa.Column('longitude', sa.Double(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.alter_column('addresses', 'name',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('beverages', 'type',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('chocolates', 'temperature',
               existing_type=mysql.ENUM('hot', 'cold'),
               nullable=False)
    op.alter_column('coffees', 'type',
               existing_type=mysql.ENUM('espresso', 'espresso machiatto', 'espresso americano', 'cappuccino', 'cappuccino latte', 'nes', 'frappe'),
               type_=sa.Enum('espresso', 'espresso machiatto', 'cappuccino', 'espresso americano', 'cappuccino latte', 'nes', 'frappe'),
               existing_nullable=False)
    op.alter_column('coffees', 'variety',
               existing_type=mysql.ENUM('80% arabica + 20% robusta', '100% arabica', 'decaffeine'),
               nullable=False)
    op.alter_column('customers', 'name',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('customers', 'address_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('freddos_flats', 'type',
               existing_type=mysql.ENUM('freddo espresso', 'freddo cappuccino', 'freddo cappuccino latte', 'flat white cold', 'flat white hot'),
               type_=sa.Enum('freddo espresso', 'espresso cappuccino', 'espresso cappuccino latte', 'flat white cold', 'flat white hot'),
               existing_nullable=False)
    op.alter_column('items', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('items', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('items', 'offer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('offers', 'cost',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=False)
    op.alter_column('orders', 'tips',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=False)
    op.alter_column('orders', 'source',
               existing_type=mysql.ENUM('Efood', 'Wolt', 'Box', 'Phone'),
               nullable=True)
    op.alter_column('orders', 'payment_method',
               existing_type=mysql.ENUM('Cash', 'Card'),
               nullable=True)
    op.alter_column('orders', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'workday_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_orders_customer_id'), table_name='orders')
    op.alter_column('smoothies', 'milk',
               existing_type=mysql.ENUM('light', 'fat', 'almond', 'coconut'),
               nullable=True)
    op.alter_column('tees', 'variety',
               existing_type=mysql.ENUM('green', 'green with pergamot', 'rooibos', 'moroccan mint', 'black with forest fruits', 'english breakfast', 'apple'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tees', 'variety',
               existing_type=mysql.ENUM('green', 'green with pergamot', 'rooibos', 'moroccan mint', 'black with forest fruits', 'english breakfast', 'apple'),
               nullable=False)
    op.alter_column('smoothies', 'milk',
               existing_type=mysql.ENUM('light', 'fat', 'almond', 'coconut'),
               nullable=False)
    op.create_index(op.f('idx_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.alter_column('orders', 'workday_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'payment_method',
               existing_type=mysql.ENUM('Cash', 'Card'),
               nullable=False)
    op.alter_column('orders', 'source',
               existing_type=mysql.ENUM('Efood', 'Wolt', 'Box', 'Phone'),
               nullable=False)
    op.alter_column('orders', 'tips',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=True)
    op.alter_column('offers', 'cost',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=True)
    op.alter_column('items', 'offer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('items', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('items', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('freddos_flats', 'type',
               existing_type=sa.Enum('freddo espresso', 'espresso cappuccino', 'espresso cappuccino latte', 'flat white cold', 'flat white hot'),
               type_=mysql.ENUM('freddo espresso', 'freddo cappuccino', 'freddo cappuccino latte', 'flat white cold', 'flat white hot'),
               existing_nullable=False)
    op.alter_column('customers', 'address_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('coffees', 'variety',
               existing_type=mysql.ENUM('80% arabica + 20% robusta', '100% arabica', 'decaffeine'),
               nullable=True)
    op.alter_column('coffees', 'type',
               existing_type=sa.Enum('espresso', 'espresso machiatto', 'cappuccino', 'espresso americano', 'cappuccino latte', 'nes', 'frappe'),
               type_=mysql.ENUM('espresso', 'espresso machiatto', 'espresso americano', 'cappuccino', 'cappuccino latte', 'nes', 'frappe'),
               existing_nullable=False)
    op.alter_column('chocolates', 'temperature',
               existing_type=mysql.ENUM('hot', 'cold'),
               nullable=True)
    op.alter_column('beverages', 'type',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('addresses', 'name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_table('v_orders_summary')
    # ### end Alembic commands ###
